apiVersion: v1
kind: Service
metadata:
  name: bur-sftp-svc
  labels:
    app: sftp
spec:
    type: ClusterIP
    ports:
      - port: 22
        targetPort: ssh
        protocol: TCP
        name: ssh
    selector:
      app: sftp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bur-sftp
  labels:
    app: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      serviceAccountName: sftp-bur-sa
      containers:
        - name: sftp-server
          image: armdocker.rnd.ericsson.se/proj-orchestration-so/sftp:1.0.0-7
          ports:
          - name: ssh
            containerPort: 22
            protocol: TCP
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
              - SYS_ADMIN
              - SYS_CHROOT
              - AUDIT_WRITE
              - CHOWN
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sftp-bur-binding
roleRef:
  kind: ClusterRole
  name: sftp-allowed-use-privileged-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sftp-bur-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sftp-bur-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sftp-allowed-use-privileged-policy
  labels:
    app: sftp
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
  # Rule to allow priveleged use in kubernetes, required when enabling
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: bur-test-sftp-ctrl-bro-allow-internal-traffic
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-ctrl-bro
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: sftp
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: bur-apigate-bro
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-ctrl-bro
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: eric-eo-api-gateway
