global:
  createClusterRoles: true
  hosts:
    gas: 'GAS_HOST_REPLACE'
    iam: 'IAM_HOST_REPLACE'
    lm: 'EO_LM_HOST_REPLACE'
  registry:
    password: 'PASSWORD_REPLACE'
    url: 'DOCKER_REGISTRY_REPLACE'
    username: 'USERNAME_REPLACE'
  support:
    ipv6:
      enabled: IPV6_ENABLE_REPLACE
  timezone: UTC
  serviceMesh:
    enabled: true
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing:
        sampling: 10
  proxy:
    tracer: zipkin
  tracer:
    zipkin:
      address: 'localhost:9411'
  externalIPv4:
    loadBalancerIP: INGRESS_IP_REPLACE
  externalIPv6:
    loadBalancerIP: ''
  clusterName: ''
  domainName: ''
  siteName: ''
  geoRedundancy:
    enabled: false
  ericsson:
    licensing:
      licenseDomains:
      - customerId: 800119
        productType: EDA
        swltId: EDA2_01
      - customerId: 800140
        productType: "Ericsson_Orchestrator"
        swltId: "STB-EVNFM-1"
      nelsConfiguration:
        primary:
          hostname: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
tags:
  eoCm: false
  eoEvnfm: false
  eoVmvnfm: false
  eoLm: true
geo-redundancy:
  enabled: false
eric-eo-lifecycle-manager:
  eric-lcm-container-registry:
    services:
      onboarding:
        enabled: true
    ingress:
      hostname: 'EO_LM_HOST_REPLACE'
      enabled: true
  eric-oss-gitops-gitea:
    enabled: true
  eric-oss-gitops-gitea-postgres:
    enabled: true
  eric-oss-gitops-fx-management:
    configuration:
      createSkeleton: true
      bootstrapFlux: true
      shardCount: 1
  git:
    externalGit:
      enabled: false
eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 20Gi
  eric-data-search-engine:
    replicaCount:
      ingest: 1
    service:
      network:
        protocol:
          IPv6: IPV6_ENABLE_REPLACE
  eric-sec-access-mgmt:
    accountManager:
      enabled: false
      inactivityThreshold: 9999
    replicaCount: 2
  eric-log-transformer:
    replicaCount: 1
    egress:
      syslog:
        enabled: false
        tls:
          enabled: true
        remoteHosts: []
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 10Gi
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
    loadBalancerIP: 'FH_SNMP_ALARM_IP_REPLACE'
  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
eric-oss-common-base:
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: 'INGRESS_IP_REPLACE'
      annotations:
        cloudProviderLB: {}
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  system-user:
    credentials:
      username: 'system-user'
      password: 'Ericsson123!'
  gas:
    defaultUser:
      username: 'gas-user'
      password: 'Ericsson123!'
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
  eric-eo-evnfm-nbi:
    eric-evnfm-rbac:
      defaultUser:
        username: 'vnfm'
        password: 'Ericsson123!'