# This override delta file was prepared for usage with main file:
# site-values/eo/ci/template/site-values-latest.yaml

global:
  nodeSelector:
    kubernetes.io/os: linux
  hosts:
    cm: 'eo-cm.EO_CM_HOST_REPLACE'
    gas: 'gas-eocm.EO_CM_HOST_REPLACE'
    gr: ''
    iam: 'iam-eocm.EO_CM_HOST_REPLACE'
  support:
    ipv6:
      enabled: false
  timezone: UTC
  ericsson:
    licensing:
      nelsConfiguration:
        primary:
          hostname: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
      licenseDomains:
        - productType: Ericsson_Orchestrator
          swltId: STB-EVNFM-1
          customerId: 800141
  externalIPv4:
    loadBalancerIP: 'EO_CM_ESA_IP_REPLACE'
  externalIPv6:
    loadBalancerIP: ''
  clusterName: eo-cm-eda
  domainName: "EO_CM_HOST_REPLACE"
  siteName: 'sitename1'
eric-oss-common-base:
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: 'EO_CM_IP_REPLACE'
  system-user:
    credentials:
      username: "system-user"
      password: "DefaultP12345!"
  eric-cnom-server:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy

eric-oss-function-orchestration-common:
  eric-am-onboarding-service:
    userSecret: container-credentials
    enabled: true
    resources:
      storage:
        size: 30Gi

eric-cloud-native-base:
  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          host: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
  eric-ctrl-bro:
    sftp:
      password: "admin"
      username: "admin"
  eric-fh-snmp-alarm-provider:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
    sendAlarm: false
    resources:
      alarmprovider:
        requests:
          cpu: "100m"
        limits:
          cpu: "500m"
  eric-fh-alarm-handler:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-data-key-value-database-rd:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-cloud-native-kvdb-rd-operand:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-data-object-storage-mn:
    global:
      security:
        tls:
          enabled: true

eric-eo-cm:
  defaultUser:
    username: ecmadmin
    password: CloudAdmin_123
  eric_eo_cm_broker_credentials:
    password: ecmNotif!23
  toscaocm:
    password: Edb_12St
    superpwd: Edb_12St
  eric-eo-cm-license-consumer-db:
    custompwd: Edb_12St
    superpwd: Edb_12St
  eric-eo-cm-onboarding-db:
    password: "1oNbo%-$!*+_ard"
    superpwd: "1oNbo%-$!*+_ard"
  eric-eo-cm-db:
    password: Edb_12St
    superpwd: Edb_12St
    db_cmdb_pass: Edb_12St
    db_ecm_pass: Edb_12St
    db_actprovadapter_pass: Edb_12St
    db_eda_pass: Edb_12St
  eric-eo-cm-ns-lcm:
    # flag for integration with scm-simulator (scmSoapMock)
    testEnv: true
    eric-eo-cm-ns-lcm-db:
      password: feq9Re*5jnRLDw
      superpwd: feq9Re*5jnRLDw
  eric-eo-cm-cust-wf:
    enabled: true
    eric-eo-cm-cust-wf-db:
      password: feq9Re*5jnRLDw
      superpwd: feq9Re*5jnRLDw
  eric-eo-cm-order-mgmt-ca:
    eric-eo-cm-order-mgmt-ca-db:
      password: MnrE%=XDg6085H
      superpwd: Mnr%$EXDg6SHCH
  eric-eo-cm-idam:
    cmdbSync_pass: Edb_12St
    domain: ".athtem.eei.ericsson.se"
    logging:
      enabled: true
      level:
        root: debug
    ecmAdmin_pass: 'CloudAdmin123'
    configStore:
      amConfigPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
      dsPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
      monitorPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
    userStore:
      dsPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
      monitorPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
    ctsStore:
      dsPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
      openamCtsPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
      monitorPassword: 'YXA2sNMmN2sPV55M7Atmg7toXuAuhzWp'
  eric-eo-cm-core:
    credentials:
      am_password: 'Ericsson123!'
    edaConfigJob:
      adminPassword: eoAdmin2021_
      onboardPassword: Admin2021$eo
      eoadminPassword: eoAdmin2021_
      ecmadminPassword: F5_#dm!N20_CM$
      ecmActPassword: emaEcm!23
    logging:
      enabled: true
      level:
        rest:
          root: info
          eo_cm: debug
        cmdb:
          root: info
          eo_cm: debug
        notification:
          root: info
          eo_cm: debug
