apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <SERACC_CLSROLB_META_NAME>-<NAMESPACE_NAME>
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount `metadata.name`
    name: <SERACC_CLSROLB_META_NAME>
    namespace: <NAMESPACE_NAME>
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
