global:
  hosts:
    iam: 'iam.dummy.se'
    gas: 'gas.dummy.se'
    uds: 'uds.dummy.se'
    so: 'so.dummy.se'
    th: 'th.dummy.se'
    adc: 'adc.dummy.se'
    gr: 'gr.dummy.se'
    aviz: 'aviz.dummy.se'
  ingressClass: eoom_iccr
  registry:
    url: 'armdocker.rnd.ericsson.se'
    username: 'dummy'
    password: 'dummy'
  serviceMesh:
    enabled: true
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 10
  proxy:
    tracer: zipkin
  tracer:
    zipkin:
      address: '1.1.1.1'
  support:
    ipv6:
      enabled: true
  timezone: UTC
  createClusterRoles: true
tags:
  so: true
  uds: true
  dmm: true
  th: true
  eas: true
  ch: true
  eca: true
  adc: true
  aindxr: true
  aviz: true
  aaug: true
  pmh: false
eric-cloud-native-base:
  eric-data-search-engine-curator:
    cronjob:
      curator:
        schedule: "0 */2 * * *"
    actions: ''
  eric-sec-access-mgmt:
    replicaCount: 2
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: '20Gi'
    sftp:
      username: 'dummy'
      password: 'dummy'
  eric-tm-ingress-controller-cr:
    enabled: true
    service:
      loadBalancerIP: '2.2.2.2'
      annotations:
        cloudProviderLB: { }
      externalTrafficPolicy: 'Local'
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        remoteHosts: []
  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: true
    persistence:
      data:
        persistentVolumeClaim:
          size: "10Gi"
  eric-data-object-storage-mn:
    objects_lifecycle_cfg: ""
    brAgent:
      properties:
        backup_data_path: "bucket1/data1.txt"
    persistentVolumeClaim:
      size: 10Gi
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
geo-redundancy:
  enabled: false
eric-oss-common-base:
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: '1.1.1.1'
      annotations:
        cloudProviderLB: {}
    externalTrafficPolicy: Cluster
  system-user:
    credentials:
      username: 'system-user'
      password: 'Ericsson123!'
  gas:
    defaultUser:
      username: 'gas-user'
      password: 'Ericsson123!'
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
  eric-gr-bur-orchestrator:
    credentials:
      username: "dummy"
      password: "dummy"
    gr:
      bro:
        autoDelete:
          backupsLimit: 10
      sftp:
        url: "10.210.220.192:22/folder"
        username: "dummy"
        password: "dummy"
      cluster:
        role: PRIMARY
        # note that the secondary_hostnames variable should only be defined if the role is set to "PRIMARY".
        # secondary_hostnames should be commented out if role is set to "SECONDARY".
eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        username: "cts-user"
        password: "Ericsson123!"
      useGasHost:
        enabled: true

eric-oss-uds:
  defaultUser:
    username: 'uds-user'
    password: 'Ericsson123!'
eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      username: 'rta-user'
      password: 'Ericsson123!'
eric-oss-config-handling:
  cps-user:
    credentials:
      username: 'cps-user'
      password: 'Ericsson123!'
  dmi-user:
    credentials:
      username: 'dmi-user'
      password: 'Ericsson123!'
eric-eo-so:
  defaultUser:
    username: 'so-user'
    password: 'Ericsson123!'

eric-oss-adc:
  ingress:
    tls:
      secretName: ves-tls-secret
  eric-oss-enm-fns:
    ignoreSubscription: true
    configuredQueries: |-
      enms:
        - name: enm-flexi7123
          periodSeconds: 60
          queries:
            - name: query1
              topic: sftp-filetrans
              dataSpace: ""
              dataCategory: PM_COUNTERS
              dataType: PM*
              nodeType: ""
              fileType: ""
              id: 0
    dmm:
      dataCatalog:
        messageBusNamespace: "eoom-deploy"
  eric-oss-sftp-filetrans-core-1:
    subsystem:
      name: "enm-flexi7123"
    dmm:
      enabled: true
      data_catalog:
        data_provider_type_version_id: "enm-flexi7123"
        data_collector_name: "pm-counter-sftp-filetrans-enm-flexi7123"
        message_bus_namespace: "eoom-deploy"
    bdr:
      enabled: true
      service_account_retry_interval: 2147483647
    spring:
      kafka:
        auto:
          start: true
        topics:
          enm_id: "enm-flexi7123"
    connected:
      systems:
        enabled: true
  eric-oss-3gpp-pm-xml-core-parser:
    enabled: true
    dmm:
      enabled: true
    bdr:
      enabled: true
      secretName: "eric-data-object-storage-mn-secret"
      accessKey: "accesskey"
      secretKey: "secretkey"
    spring:
      kafka:
        topics:
          auto:
            start: false
        admin:
          request_timeout_ms: 60000
    connected:
      systems:
        enabled: true
    subsystem:
      name: "core-pm-counter-sftp-file-transfer"
    probes:
      eric-oss-3gpp-pm-xml-core-parser:
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          initialDelaySeconds: 90
          periodSeconds: 15
  eric-oss-sftp-filetrans:
    enabled: false
