global:
  hosts:
    so: "SO_HOST_REPLACE"
    iam: "IAM_HOST_REPLACE"
    pf: "PF_HOST_REPLACE"
    uds: "UDS_HOST_REPLACE"
    gr: "GR_HOST_REPLACE"
    gas: "GAS_HOST_REPLACE"
    adc: "ADC_HOST_REPLACE"
    appmgr: "APPMGR_HOST_REPLACE"
  registry:
    # If deploying from the director node on a CCD environment, the url can be retrieved using:
    # kubectl get ingress eric-lcm-container-registry-ingress -n kube-system -o jsonpath="{.spec.tls[*].hosts[0]}"; echo
    url: "DOCKER_REGISTRY_REPLACE"
    # Docker registry username
    username: "USERNAME_REPLACE"
    # Docker registry password
    password: "PASSWORD_REPLACE"
  support:
    ipv6:
      enabled: false
  timezone: UTC
  createClusterRoles: true
  ingressClass: oss_iccr
  iccrAppIngresses: false
  serviceMesh:
    enabled: false
    annotations:
      serviceMesh: 5.0.0+114
  networkPolicy:
    enabled: true
# Warning! If changing these application tags from true to false and that application
# is already installed, then that application will be removed and data will be lost!
tags:
  so: false
  pf: false
  uds: false
  adc : false
  dmm : false
  th : false
  eas: false
  appmgr: false
  ch: false
  ta: false

eric-oss-common-base:
  system-user:
    credentials:
      username: system-user
      password: Ericsson123!

  eric-eo-api-gateway:
    iam:
      kubernetesSecret: eric-oss-common-base-iam-client-secret

  service-mesh-ingress-gateway:
    enabled: false
    service:
      loadBalancerIP: ''
      annotations:
        cloudProviderLB: {}

  gas:
    defaultUser:
      username: gas-user
      password: Ericsson123!

eric-cloud-native-base:
  eric-sec-access-mgmt:
    replicaCount: 2
    ingress:
      type: nginx
  eric-tm-ingress-controller-cr:
    enabled: false
    service:
      loadBalancerIP: ''
      annotations:
        cloudProviderLB: {}

  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 15Gi
    sftp:
      username: dummy
      password: dummy

  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: false
    persistence:
      data:
        persistentVolumeClaim:
          size: 10Gi

eric-eo-so:
  defaultUser:
    username: so-user
    password: Ericsson123!

eric-oss-pf:
  defaultUser:
    username: pf-user
    password: Ericsson123!

eric-oss-uds:
  defaultUser:
    username: uds-user
    password: Ericsson123!

eric-oss-ericsson-adaptation:
  stubs:
    enabled: false

eric-oss-config-handling:
  cps-user:
    credentials:
      username: cps-user
      password: Ericsson123!
  dmi-user:
    credentials:
      username: dmi-user
      password: Ericsson123!

eric-oss-app-mgr:
  eric-lcm-helm-executor:
    docker-registry:
      url: "https://APPMGR_HOST_REPLACE/app/manager/registry/"
