# This override delta file was prepared for usage with main file:
# site-values/ci/site-values-latest.yaml

# used solely for the purpose of EOOM PoC

global:
  security:
    tls:
      enabled: true

eric-oss-ericsson-adaptation:
  eric-oss-enm-notification-adapter:
    enabled: false
  eric-oss-enm-notification-simulator:
    enabled: false
  eric-oss-enm-discovery-adapter:
    enabled: false
  eric-oss-enm-model-adapter:
    enabled: false
  eric-oss-ran-topology-adapter:
    enabled: false
  eric-oss-enm-discovery-adapter-database-pg:
    enabled: false
  eric-oss-enm-notification-adapter-database-pg:
    enabled: false
  eric-oss-enm-model-adapter-database-pg:
    enabled: false


eric-cloud-native-base:
  eric-sec-access-mgmt:
    http:
      hostValidation:
        allowedHosts: keycloak.6637-iccr.flexilab.seli.gic.ericsson.se,ecm.6637-iccr.flexilab.seli.gic.ericsson.se,keycloak.7106-iccr.flexilab.seli.gic.ericsson.se,ecm.7106-iccr.flexilab.seli.gic.ericsson.se,keycloak.7123-iccr.flexilab.seli.gic.ericsson.se,ecm.7123-iccr.flexilab.seli.gic.ericsson.se,keycloak.7124-iccr.flexilab.seli.gic.ericsson.se,ecm.7124-iccr.flexilab.seli.gic.ericsson.se