# This override delta file was prepared for usage with main file:
# site-values/eo/ci/template/site-values-latest.yaml

# Enabling stubs from SO
stubs:
  enabled: true
eric-eo-evnfm:
  eric-lcm-container-registry:
    persistence:
      persistentVolumeClaim:
        size: "50Gi"
    resources:
      brAgent:
        limits:
          memory: 1500Mi
          cpu: 1500m
          ephemeral-storage: 20Gi
  eric-global-lcm-container-registry:
    hostname: 'dummy'
    username: 'dummy'
    password: 'dummy'
  eric-am-onboarding-service:
    onboarding:
      skipCertificateValidation: false
  application-manager-postgres:
    probes:
      logshipper:
        livenessProbe:
          initialDelaySeconds: 300
eric-eo-so:
  stubs:
    enabled: true
# Fill only if deploying Ericsson Adaptation (EAS)
eric-oss-ericsson-adaptation:
  eric-eo-enm-stub:
    enabled: true
  eric-oss-enm-notification-simulator:
    enabled: true
eric-oss-uds:
  eric-oss-uds-policy-artifact-ui:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
eric-cloud-native-base:
  eric-lm-combined-server:
    licenseServerClient:
      licenseServer:
        thrift:
          # Mandatory: licenseServerClient.licenseServer.thrift.host - The NELS thrift server address or service name
          host: ""
  #setting podAffinity to soft as mentioned in object storage documentation to be able to deploy in clusters with 3 worker nodes(N239 Openshift)
  #need to discuss, leave it as is, or request additional node for N239 cluster
  eric-data-object-storage-mn:
    affinity:
      podAntiAffinity: 'soft'
  eric-fh-snmp-alarm-provider:
    sendAlarm: True
  eric-data-key-value-database-rd:
    resources:
      kvdbOperator:
        limits:
          cpu: 100m
          memory: 200Mi
          ephemeral-storage: 2Gi