# This override delta file was prepared for usage with main file:
# site-values/eo/ci/template/site-values-latest.yaml


global:
  nodeSelector:
    kubernetes.io/os: linux
  ericsson:
    licensing:
      licenseDomains:
      - productType: "Ericsson_Orchestrator"
        swltId: "STB-EVNFM-1"
        customerId: 800141
        applicationId: "800141_STB-EVNFM-1_Ericsson_Orchestrator"
      nelsConfiguration:
        primary:
          hostname: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"

eric-oss-common-base:
  eric-cnom-server:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
eric-eo-evnfm:
  eric-lcm-container-registry:
    persistence:
      persistentVolumeClaim:
        size: "40Gi"
    resources:
      brAgent:
        limits:
          memory: 1500Mi
          cpu: 1500m
          ephemeral-storage: 20Gi
  eric-global-lcm-container-registry:
    hostname: 'dummy'
    username: 'dummy'
    password: 'dummy'
  application-manager-postgres:
    probes:
      logshipper:
        livenessProbe:
          initialDelaySeconds: 300
eric-oss-function-orchestration-common:
  eric-am-onboarding-service:
    onboarding:
      skipCertificateValidation: false
    ephemeral:
      volume:
        size: 30Gi

eric-cloud-native-base:
  eric-si-application-sys-info-handler:
    asih:
      uploadSwimInformation: false
    applicationInfoService:
      port: 9095
  eric-lm-combined-server:
    labels:
      eric-si-application-sys-info-handler-access: "true"
    licenseServerClient:
      asih:
        port: 8080
      licenseServer:
        thrift:
          # Mandatory: licenseServerClient.licenseServer.thrift.host - The NELS thrift server address or service name
          host: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
          port: 9095
  eric-fh-snmp-alarm-provider:
    sendAlarm: false
    service:
      annotations:
        sharedVIPLabel: "shared-vip"
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-fh-alarm-handler:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-cloud-native-kvdb-rd-operand:
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-tm-ingress-controller-cr:
    service:
      externalTrafficPolicy: Cluster
  eric-data-key-value-database-rd:
    resources:
      kvdbOperator:
        limits:
          cpu: 100m
          memory: 200Mi
          ephemeral-storage: 2Gi
    imageCredentials:
      pullSecret: k8s-registry-secret-legacy
  eric-sec-key-management:
    logLevel: debug
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 20Gi