global:
  createClusterRoles: true
  hosts:
    gas: 'GAS_HOST_REPLACE'
    gr: 'GR_HOST_REPLACE'
    iam: 'IAM_HOST_REPLACE'
    pf: 'PF_HOST_REPLACE'
    so: 'SO_HOST_REPLACE'
    uds: 'UDS_HOST_REPLACE'
    vnfm: 'VNFM_HOST_REPLACE'
    cm: 'CM_HOST_REPLACE'
    th: 'TH_HOST_REPLACE'
  ingressClass: eo_iccr
  registry:
    password: 'PASSWORD_REPLACE'
    url: 'DOCKER_REGISTRY_REPLACE'
    username: 'USERNAME_REPLACE'
  support:
    ipv6:
      enabled: IPV6_ENABLE_REPLACE
  timezone: UTC
  serviceMesh:
    enabled: false
  meshConfig:
    enableTracing: false
    defaultConfig:
      tracing:
        sampling: 10
  proxy:
    tracer: zipkin
  tracer:
    zipkin:
      address: 'localhost:9411'
  networkPolicy:
    enabled: false
  externalIPv4:
    loadBalancerIP: INGRESS_IP_REPLACE
  clusterName: ''
  domainName: ''
  ericsson:
    licensing:
      licenseDomains:
      - customerId: 800119
        productType: EDA
        swltId: EDA2_01
tags:
  eoCm: false
  eoEvnfm: false
  eoPf: false
  eoSo: false
  eoUds: false
  eoVmvnfm: false
eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 20Gi
    sftp:
      password: 'dummy'
      username: 'dummy'
  eric-data-search-engine:
    service:
      network:
        protocol:
          IPv6: IPV6_ENABLE_REPLACE
  eric-sec-access-mgmt:
    replicaCount: 2
  eric-tm-ingress-controller-cr:
    service:
      loadBalancerIP: 'INGRESS_IP_REPLACE'
      annotations:
        cloudProviderLB: {}
      externalTrafficPolicy: Local
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        remoteHosts: []
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 10Gi
geo-redundancy:
  enabled: false
eric-oss-common-base:
  system-user:
    credentials:
      username: 'system-user'
      password: 'Ericsson123!'
  gas:
    defaultUser:
      username: 'gas-user'
      password: 'Ericsson123!'
  eric-eo-usermgmt:
    replicaCount: 2
  eric-eo-usermgmt-ui:
    replicaCount: 2
  eric-eo-evnfm-nbi:
    eric-evnfm-rbac:
      defaultUser:
        username: 'vnfm'
        password: 'Ericsson123!'
  eric-gr-bur-orchestrator:
    credentials:
      username: 'dummy'
      password: 'dummy'
    gr:
      bro:
        autoDelete:
          backupsLimit: 10
      sftp:
        url: 'dummy:22/path/'
        username: 'dummy'
        password: 'dummy'
      cluster:
        role: 'PRIMARY'
        secondary_hostnames:
        - 'dummy'
      registry:
        secondarySiteContainerRegistryHostname: 'fakehostname.com'
eric-oss-uds:
  defaultUser:
    username: 'uds-user'
    password: 'Ericsson123!'
eric-oss-pf:
  defaultUser:
    username: 'pf-user'
    password: 'Ericsson123!'
eric-oss-ericsson-adaptation:
  eric-oss-ran-topology-adapter:
    rtaUser:
      username: 'rta-user'
      password: 'Ericsson123!'
eric-oss-config-handling:
  cps-user:
    credentials:
      username: 'cps-user'
      password: 'Ericsson123!'
  dmi-user:
    credentials:
      username: 'dmi-user'
      password: 'Ericsson123!'
eric-topology-handling:
  eric-oss-common-topology-svc:
    eric-oss-cmn-topology-svc-core:
      defaultUser:
        username: 'cts-user'
        password: 'Ericsson123!'
eric-eo-so:
  defaultUser:
    username: 'so-user'
    password: 'Ericsson123!'
eric-eo-evnfm-vm:
  eric-vnflcm-service:
    oss:
      secretName: null
    persistentVolumeClaim:
      size: 20Gi
    service:
      enabled: VNFLCM_SERVICE_DEPLOY_REPLACE
      loadBalancerIP: 'VNFLCM_SERVICE_IP_REPLACE'
      externalTrafficPolicy: Local
eric-oss-function-orchestration-common:
   eric-am-onboarding-service: # SM-149743
      userSecret: container-credentials
eric-eo-evnfm:
  eric-am-common-wfs: # SM-149743
      userSecret: container-credentials
  eric-lcm-container-registry:
    ingress:
      hostname: 'VNFM_REGISTRY_HOST_REPLACE'
    persistence:
      persistentVolumeClaim:
        size: 10Gi
  eric-global-lcm-container-registry:
    hostname: ''
    username: ''
    password: ''
  eric-lcm-helm-chart-registry:
    ingress:
      enabled: HELM_REGISTRY_DEPLOY_REPLACE
      hostname: 'HELM_CHART_HOST_REPLACE'
    env:
      secret:
        BASIC_AUTH_USER: 'evnfm'
        BASIC_AUTH_PASS: 'evnfm'
  eric-vnfm-orchestrator-service:
    oss:
      topology:
        secretName: null
    smallstack:
      application: true
eric-eo-cm:
  defaultUser:
    username: ''
    password: ''
  eric_eo_cm_broker_credentials:
    password: ''
  eric-eo-cm-db:
    password: ''
    superpwd: ''
  eric-eo-cm-ns-lcm:
    eric-eo-cm-ns-lcm-db:
      password: ''
      superpwd: ''
  eric-eo-cm-cust-wf:
    eric-eo-cm-cust-wf-db:
      password: ''
      superpwd: ''
  eric-eo-cm-order-mgmt-ca:
    eric-eo-cm-order-mgmt-ca-db:
      password: ''
      superpwd: ''
  eric-eo-cm-idam:
    domain: ''
  eric-eo-cm-core:
    edaConfigJob:
      onboardPassword: ''
      eoadminPassword: ''
      ecmadminPassword: ''
      ecmActPassword: ''
      scmClientId: ''
      scmClientSecret: ''
  eric-eo-cm-onboarding:
    enabled: false
