global:
  createClusterRoles: true
  hosts:
    gas: 'GAS_HOST_REPLACE'
    gr: 'GR_HOST_REPLACE'
    iam: 'IAM_HOST_REPLACE'
    vnfm: 'VNFM_HOST_REPLACE'
    cm: 'CM_HOST_REPLACE'
  registry:
    password: 'PASSWORD_REPLACE'
    url: 'DOCKER_REGISTRY_REPLACE'
    username: 'USERNAME_REPLACE'
  support:
    ipv6:
      enabled: IPV6_ENABLE_REPLACE
  timezone: UTC
  externalIPv4:
    loadBalancerIP: FH_SNMP_ALARM_IP_REPLACE
  externalIPv6:
    loadBalancerIP: ''
  clusterName: ''
  domainName: ''
  siteName: ''
  ericsson:
    licensing:
      licenseDomains:
      - customerId: 800119
        productType: EDA
        swltId: EDA2_01
      - customerId: 800140
        productType: "Ericsson_Orchestrator"
        swltId: "STB-EVNFM-1"
  licensing:
    sites:
    # Mandatory: global.licensing.sites[0].hostname - The NELS thrift server address or service name will be removed in SEP Note: Ticket created for removal as part of the IDUN-112276
    - hostname: "nelsaas-vnf2-thrift.sero.gic.ericsson.se"
tags:
  eoCm: false
  eoEvnfm: false
  eoVmvnfm: false
eric-cloud-native-base:
  eric-ctrl-bro:
    persistence:
      persistentVolumeClaim:
        size: 20Gi
  eric-data-search-engine:
    # will be removed in Sep jira raised IDUN_112520 https://gerrit.ericsson.se/#/c/17396241/
    service:
      network:
        protocol:
          IPv6: IPV6_ENABLE_REPLACE
  eric-sec-access-mgmt:
    accountManager:
      enabled: false
      inactivityThreshold: 9999
  eric-log-transformer:
    egress:
      syslog:
        enabled: false
        tls:
          enabled: true
        remoteHosts: []
  eric-data-object-storage-mn:
    persistentVolumeClaim:
      size: 10Gi
  eric-fh-snmp-alarm-provider:
    # removed in April from required in optinal values in here :https://gerrit.ericsson.se/#/c/17744530/ ticket in backlog for removal
    sendAlarm: false
    loadBalancerIP: 'FH_SNMP_ALARM_IP_REPLACE'
geo-redundancy:
  enabled: false
eric-oss-function-orchestration-common:
  eric-eo-evnfm-nbi:
    eric-evnfm-rbac:
      defaultUser:
        username: 'vnfm'
        password: 'Ericsson123!'
  eric-am-onboarding-service:
    #will be removed in 24.16 sprint work is ongoing as part of the ticket EO-169853 and EO-178949
    userSecret: container-credentials
eric-oss-common-base:
  service-mesh-ingress-gateway:
    service:
      loadBalancerIP: 'INGRESS_IP_REPLACE'
      annotations:
        cloudProviderLB: {}
  sessionTokens:
    maxSessionDurationSecs: 36000
    maxIdleTimeSecs: 1800
  system-user:
    credentials:
      username: 'system-user'
      password: 'Ericsson123!'
  gas:
    defaultUser:
      username: 'gas-user'
      password: 'Ericsson123!'
  eric-gr-bur-orchestrator:
    # will be removed in Nov ticket IDUN-119566
    credentials:
      username: 'dummy'
      password: 'dummy'
    gr:
      bro:
        autoDelete:
          backupsLimit: 5
      sftp:
        url: 'dummy:22/path/'
        username: 'dummy'
        password: 'dummy'
      cluster:
        role: 'PRIMARY'
        secondary_hostnames:
        - 'GR_SECONDARY_HOST_REPLACE'
      registry:
        secondarySiteContainerRegistryHostname: 'GR_SECONDARY_HOST_REPLACE'
eric-eo-evnfm-vm:
  eric-vnflcm-service:
    oss:
      secretName: null
    persistentVolumeClaim:
      size: 20Gi
    service:
      enabled: VNFLCM_SERVICE_DEPLOY_REPLACE
      loadBalancerIP: 'VNFLCM_SERVICE_IP_REPLACE'
      externalTrafficPolicy: Local
    ha:
      enabled: false
      persistentVolumeClaim:
        storageClassName: null
eric-eo-evnfm:
  eric-lcm-container-registry:
    enabled: true
    highAvailability: false #will be removed in July EO-174064
    ingress:
      hostname: 'VNFM_REGISTRY_HOST_REPLACE'
    persistence:
      #will be removed in in July EO-174064
      persistentVolumeClaim:
        size: 10Gi
  eric-global-lcm-container-registry:
    # Needs to stay for legacy EO-178949
    hostname: 'GLOBAL_VNFM_REGISTRY_HOST_REPLACE'
    username: ''
    password: ''
  eric-lcm-helm-chart-registry:
    ingress:
      enabled: HELM_REGISTRY_DEPLOY_REPLACE
      #needs to stay for now ticket EO-178949
      hostname: 'HELM_CHART_HOST_REPLACE'
    env:
      secret:
        BASIC_AUTH_USER: 'evnfm'
        BASIC_AUTH_PASS: 'evnfm'
  eric-vnfm-orchestrator-service:
    oss:
      topology:
        secretName: null
    smallstack:
      application: true
  eric-am-common-wfs:
    helm:
      url: "HELM_CHART_HOST_REPLACE"
    dockerRegistry:
      secret: null
    userSecret: container-credentials # SM-149743 will be removed in 24.16 sprint work is ongoing as part of the ticket EO-169853 and EO-178949
  services:
    onboarding:
      enabled: true
eric-eo-cm:
  defaultUser:
    password: ''
  eric_eo_cm_broker_credentials:
    password: ''
  eric-eo-cm-db:
    password: ''
    superpwd: ''
    db_cmdb_pass: ''
    db_ecm_pass: ''
    db_actprovadapter_pass: ''
    db_eda_pass: ''
  eric-eo-cm-ns-lcm:
    eric-eo-cm-ns-lcm-db:
      password: ''
      superpwd: ''
  eric-eo-cm-cust-wf:
    enabled: false
    eric-eo-cm-cust-wf-db:
      #will be removed when eoCm tag is removed-optional value
      password: ''
      superpwd: ''
  eric-eo-cm-order-mgmt-ca:
    eric-eo-cm-order-mgmt-ca-db:
      password: ''
      superpwd: ''
  eric-eo-cm-idam:
    domain: ''
    cmdbSync_pass: ''
    configStore:
      amConfigPassword: ''
      dsPassword: ''
      monitorPassword: ''
    userStore:
      dsPassword: ''
      monitorPassword: ''
    ctsStore:
      dsPassword: ''
      openamCtsPassword: ''
      monitorPassword: ''
    ecmAdmin_pass: ''
  eric-eo-cm-core:
    credentials:
      am_password: ''
    edaConfigJob:
      eoadminPassword: ''  # Activation password for "eoadmin@admin.local"
      adminPassword: ''    # Activation password for "admin@admin.local"
      ecmadminPassword: '' # Activation password for "ecmadmin@admin.local"
      ecmActPassword: ''   # Activation password for "ecmAct"
  eric-eo-cm-onboarding:
    # will be removed when eocm tag is removed, optional value
    enabled: false
  eric-eo-cm-license-consumer-db:
    custompwd: ''
    superpwd: ''
  toscaocm:
    password: ''
    superpwd: ''
  eric-eo-cm-gr:
    # will be removed with eoCm values-optional value
    grConfiguration:
      thisSite:
        namespace: ''
        tlsProxyIP: ''
      otherSite:
        name: ''
        namespace: ''
        tlsProxyIP: ''
